# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b5e5d0217be0bd0cf3b505804353c337fe518ffb323ebbf9eabb93f3e4ee383a7e702d17b5d2ba94a4d62454d331e14ff92c119c605dde575ea44bf84129f7d

test:
  secret_key_base: 0ef5889b99ae04d52d55550fa4719513147f98fa7450f6a24b5438c3afc004056d547b522851b3cb76512bf98f8d93f94fa5dd9e05e6db5f01cb35d3dda0d1cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
